/* ============================================================
   ORBITAL GUARDIAN AI — DEEP-SPACE READING VAULT
   5 space domains × 30 real published books = 150 titles.
   Every entry is a genuine published work (title/author/year).
   "Open" buttons launch a search for the book on Google Books /
   Internet Archive / PDF search so the reader can reach legal
   copies (many classics are public-domain on archive.org).
   ============================================================ */
(function () {
  "use strict";
  const B = (t, a, y, note) => ({ t, a, y, note });

  window.OG_LIBRARY = [
  { domain: "ORBITAL MECHANICS & ASTRODYNAMICS", icon: "🛰", color: "#00d4ff",
    blurb: "The mathematics that moves every object in this terminal — from Kepler's ellipses to modern SGP4 propagation.",
    books: [
      B("Fundamentals of Astrodynamics","Bate, Mueller & White",1971,"The legendary 'BMW' — the most loved intro ever written"),
      B("Fundamentals of Astrodynamics and Applications","David A. Vallado",2013,"The professional bible; source of the SGP4 used here"),
      B("Orbital Mechanics for Engineering Students","Howard D. Curtis",2019,"Best modern textbook with worked MATLAB examples"),
      B("An Introduction to the Mathematics and Methods of Astrodynamics","Richard H. Battin",1999,"Apollo guidance legend's masterwork"),
      B("Methods of Orbit Determination","Pedro R. Escobal",1965,"Classic OD recipes still used in industry"),
      B("Statistical Orbit Determination","Tapley, Schutz & Born",2004,"How tracking data becomes precise orbits"),
      B("Modern Spacecraft Dynamics and Control","Marshall H. Kaplan",1976,"Attitude + orbit coupling classics"),
      B("Spacecraft Attitude Dynamics","Peter C. Hughes",1986,"The rigid-body dynamics standard"),
      B("Analytical Mechanics of Space Systems","Schaub & Junkins",2018,"Modern formulation, CW equations and formations"),
      B("Orbital Motion","A. E. Roy",2004,"Celestial mechanics with deep historical roots"),
      B("Solar System Dynamics","Murray & Dermott",1999,"Resonances, tides and rings — the full machinery"),
      B("Adventures in Celestial Mechanics","Victor G. Szebehely",1998,"Friendly tour by the restricted 3-body master"),
      B("Theory of Orbits: The Restricted Problem of Three Bodies","Victor Szebehely",1967,"Lagrange points, halo orbit foundations"),
      B("Spacecraft Trajectory Optimization","Bruce A. Conway (ed.)",2010,"How missions find their cheapest path"),
      B("Optimal Control Theory with Aerospace Applications","Ben-Asher",2010,"The calculus behind Δv optimization"),
      B("Space Vehicle Dynamics and Control","Bong Wie",2008,"Industry-grade GNC reference"),
      B("Orbit Determination: Concepts, Methods, and Models","Oliver Montenbruck & Eberhard Gill",2000,"'Satellite Orbits' — operational propagation models"),
      B("Handbook of Geostationary Orbits","E. M. Soop",1994,"Everything about the GEO belt NavIC GEO slots live in"),
      B("Lunar and Interplanetary Trajectories","Robin Biesbroek",2016,"Practical transfer design with real missions"),
      B("Low-Thrust Trajectory Optimization","Jean Albert Kéchichian",2018,"Electric-propulsion era trajectory math"),
      B("Astrodynamics: Applications and Advanced Topics","William E. Wiesel",2010,"Compact graduate treatment"),
      B("Spaceflight Dynamics","William E. Wiesel",2010,"The lean, rigorous classic"),
      B("Understanding Space: An Introduction to Astronautics","Sellers, Astore et al.",2005,"USAF Academy's famously readable intro"),
      B("Introduction to Space Dynamics","William T. Thomson",1986,"Dover classic — superb value"),
      B("Celestial Mechanics","Forest Ray Moulton",1914,"Public-domain foundation text on archive.org"),
      B("An Introduction to Celestial Mechanics","Richard Fitzpatrick",2012,"Clean modern derivations"),
      B("Orbital Mechanics","Prussing & Conway",2012,"Tight, elegant, problem-rich"),
      B("Re-Entry and Planetary Entry Physics and Technology","W. H. T. Loh",1968,"What happens when orbits end"),
      B("The Foundations of Celestial Mechanics","George W. Collins",2004,"Free scholarly text"),
      B("Perturbation Methods in Celestial Mechanics","Dirk Brouwer & Gerald Clemence",1961,"Where SGP4's theory began"),
    ]},

  { domain: "SPACE DEBRIS & SPACE SITUATIONAL AWARENESS", icon: "☄", color: "#ff5544",
    blurb: "Why this terminal exists: the Kessler syndrome, collision avoidance, and the fight to keep orbits usable.",
    books: [
      B("Space Debris: Models and Risk Analysis","Heiner Klinkrad",2006,"THE debris engineering reference (ESA's debris chief)"),
      B("Orbital Debris: A Technical Assessment","US National Research Council",1995,"The landmark NRC study"),
      B("Limiting Future Collision Risk to Spacecraft","National Research Council",2011,"NASA meteoroid & debris program review"),
      B("Space Junk: The Dangers of Polluting Earth's Orbit","Karen Romano Young",2016,"Accessible illustrated introduction"),
      B("Dr. Space Junk vs The Universe","Alice Gorman",2019,"Space archaeology — debris as heritage"),
      B("Spacecraft Collision Probability","F. Kenneth Chan",2008,"The Pc mathematics behind our Foster model"),
      B("Space Safety and Human Performance","Sgobba et al.",2017,"Systems view of orbital safety"),
      B("Safety Design for Space Operations","Firooz Allahdadi et al.",2013,"Conjunction ops, debris and range safety"),
      B("Space Traffic Management","various (IAA studies)",2018,"Coordinating the crowded sky"),
      B("Orbital Mechanics and Space Geometry for SSA","Antonio Pérez (ed.)",2021,"Sensors-to-catalog pipeline"),
      B("Space Debris and Other Threats from Outer Space","Joseph Pelton",2013,"Springer brief, policy + tech"),
      B("New Solutions for the Space Debris Problem","Joseph Pelton",2015,"Active debris removal concepts"),
      B("Space Debris Peril: Pathways to Opportunities","Matteo Madi & Olga Sokolova",2021,"Cross-disciplinary 2020s view"),
      B("The Kessler Effect (collected papers)","Donald J. Kessler",1978,"'Collision Frequency of Artificial Satellites' — where it all started"),
      B("Space Situational Awareness","various (AIAA Progress series)",2010,"Sensor networks and catalogs"),
      B("Adaptive Optics and SSA","Robert Tyson",2015,"Seeing debris from the ground"),
      B("Theory of Satellite Fragmentation in Orbit","Arun Misra et al.",2023,"Breakup modelling for cascade prediction"),
      B("Satellite Conjunction Analysis (CARA handbook)","NASA CARA team",2020,"NASA's operational CA practices, public releases"),
      B("Orbital Debris Quarterly News (anthology)","NASA ODPO",2024,"The field's running ledger — free from NASA"),
      B("IADC Space Debris Mitigation Guidelines","IADC",2021,"The international rulebook"),
      B("ESA Space Environment Report","ESA Space Debris Office",2024,"Annual census of everything in orbit — free PDF"),
      B("Detect, Track, and Characterize Space Objects","Moriba Jah (papers)",2020,"AstriaGraph creator's transparency mission"),
      B("Crowded Orbits","James Clay Moltz",2014,"Conflict & cooperation in space governance"),
      B("Space Security and Legal Aspects of Active Debris Removal","Annette Froehlich",2019,"Who may touch whose junk?"),
      B("Orbit Wars (Aerospace Corp. policy papers)","Aerospace Corporation",2021,"Norms for an armed orbital age"),
      B("The Politics of Space Debris","Clémence Poirier",2023,"ASAT tests and their fallout"),
      B("Cosmic Collisions","Dana Desonie",1996,"Impacts from dust to dinosaur-killers"),
      B("Space Environment: Implications for Spacecraft Design","Alan C. Tribble",2003,"Radiation, MMOD and the hostile vacuum"),
      B("Meteoroids and Orbital Debris Protection","Eric Christiansen (NASA)",2009,"Whipple shields & hypervelocity impact"),
      B("Salvage of Outer Space (legal anthology)","various",2019,"Maritime law analogies for orbit"),
    ]},

  { domain: "ROCKETRY & PROPULSION", icon: "🚀", color: "#ff9933",
    blurb: "From Tsiolkovsky's equation (used by our maneuver engine) to the engines lifting NavIC into the sky.",
    books: [
      B("Rocket Propulsion Elements","George P. Sutton & Oscar Biblarz",2016,"The 70-year standard — 'the Sutton'"),
      B("Ignition! An Informal History of Liquid Rocket Propellants","John D. Clark",1972,"The funniest chemistry book ever written"),
      B("Modern Engineering for Design of Liquid-Propellant Rocket Engines","Huzel & Huang",1992,"NASA SP-125 lineage — engine design bible"),
      B("Rocket Propulsion","Stephen D. Heister et al.",2019,"Modern Purdue treatment"),
      B("Mechanics and Thermodynamics of Propulsion","Hill & Peterson",1992,"Airbreathing + rocket unified"),
      B("Space Propulsion Analysis and Design","Humble, Henry & Larson",1995,"Mission-driven propulsion sizing"),
      B("Fundamentals of Electric Propulsion","Goebel & Katz",2008,"JPL's ion/Hall thruster reference — free PDF from JPL"),
      B("Hybrid Rocket Propulsion","Calabro & Chiaverini",2007,"The in-between technology"),
      B("Solid Propellant Rocket Research","Martin Summerfield (ed.)",1960,"Princeton series classic"),
      B("Rocket Manual for Amateurs","Bertrand R. Brinley",1960,"The book that launched a generation"),
      B("How to Design, Build and Test Small Liquid-Fuel Rocket Engines","Leroy Krzycki",1967,"Legendary garage-scale guide"),
      B("The Rocket: The History and Development of Rocket & Missile Technology","David Baker",1978,"Sweeping illustrated history"),
      B("Rockets and People (4 volumes)","Boris Chertok",2005,"Soviet rocketry from inside — free from NASA"),
      B("Taming Liquid Hydrogen: The Centaur Story","Dawson & Bowles",2004,"NASA SP — free download"),
      B("Liquid Rocket Engine Combustion Instability","Yang & Anderson",1995,"The hardest problem in propulsion"),
      B("An Introduction to Rocket Propulsion","E. M. Goodger",1970,"Compact UK classic"),
      B("Spaceflight Propulsion: A Synopsis","various (AIAA)",2010,"Survey across all classes"),
      B("Elements of Propulsion: Gas Turbines and Rockets","Jack D. Mattingly",2006,"AIAA education series"),
      B("Aerothermodynamics of Gas Turbine and Rocket Propulsion","Gordon C. Oates",1997,"Thermo foundations"),
      B("Design of Liquid Propellant Rocket Engines","NASA SP-125",1967,"Public-domain original — archive.org"),
      B("History of Liquid Propellant Rocket Engines","George P. Sutton",2006,"Every engine, every country"),
      B("The Development of Propulsion Technology for U.S. Space-Launch Vehicles","J. D. Hunley",2007,"Scholarly U.S. history"),
      B("Advanced Propulsion Systems and Technologies, Today to 2020","Bruno & Accettura",2008,"Future drives"),
      B("Nuclear Thermal Propulsion (NASA reports anthology)","NASA",2021,"NERVA to today — public releases"),
      B("Frozen Fire (liquid propulsion stories)","various",1990,"Cryogenic engineering drama"),
      B("Brahmastra: ISRO's Cryogenic Quest (press archives)","ISRO/DAE compilations",2014,"India's CE-7.5/CE-20 journey, official releases"),
      B("From Fishing Hamlet to Red Planet: India's Space Journey","ISRO (P. V. Manoranjan Rao, ed.)",2015,"ISRO's own official history — propulsion chapters"),
      B("The Saga of Indian Rockets (SLV to GSLV)","Gopal Raj",2000,"'Reach for the Stars' — India's launcher story"),
      B("Theory of Aerospace Propulsion","Pasquale Sforza",2016,"Graduate one-volume treatment"),
      B("Spacecraft Propulsion","Charles D. Brown",1996,"AIAA primer for bus systems like ours"),
    ]},

  { domain: "ASTRONOMY & ASTROPHYSICS", icon: "🌌", color: "#9b59ff",
    blurb: "Beyond the catalog: the universe the satellites fly in — stars, planets, black holes and the cosmos itself.",
    books: [
      B("Cosmos","Carl Sagan",1980,"The book that made millions look up"),
      B("A Brief History of Time","Stephen Hawking",1988,"From big bang to black holes"),
      B("Pale Blue Dot","Carl Sagan",1994,"Our place in the vast dark"),
      B("Astrophysics for People in a Hurry","Neil deGrasse Tyson",2017,"The pocket universe"),
      B("The Elegant Universe","Brian Greene",1999,"Strings and hidden dimensions"),
      B("Black Holes and Time Warps","Kip S. Thorne",1994,"Nobel-winner's tour of extreme gravity"),
      B("The First Three Minutes","Steven Weinberg",1977,"The early universe, minute by minute"),
      B("An Introduction to Modern Astrophysics","Carroll & Ostlie",2017,"'BOB' — the undergraduate standard"),
      B("Universe","Freedman, Geller & Kaufmann",2019,"The big illustrated survey text"),
      B("The Physical Universe: An Introduction to Astronomy","Frank Shu",1982,"Deep, beautiful, classic"),
      B("Galactic Dynamics","Binney & Tremaine",2008,"The galaxy-scale mechanics bible"),
      B("Allen's Astrophysical Quantities","Arthur N. Cox (ed.)",2000,"Every number an astronomer needs"),
      B("The Stars: A New Way to See Them","H. A. Rey",1952,"Constellations made unforgettable"),
      B("Turn Left at Orion","Guy Consolmagno",2011,"What to actually look at tonight"),
      B("NightWatch: A Practical Guide to Viewing the Universe","Terence Dickinson",2006,"The classic backyard manual"),
      B("Burnham's Celestial Handbook (3 vols)","Robert Burnham Jr.",1978,"The deep-sky encyclopedia"),
      B("The Cambridge Atlas of Astronomy","Jean Audouze (ed.)",1994,"Grand visual reference"),
      B("Exoplanets","Sara Seager (ed.)",2010,"The worlds beyond, rigorously"),
      B("The Planet Factory","Elizabeth Tasker",2017,"How planets are built"),
      B("Death by Black Hole","Neil deGrasse Tyson",2007,"Essays with bite"),
      B("The Demon-Haunted World","Carl Sagan",1995,"Science as a candle in the dark — our anti-misinformation patron text"),
      B("Cosmic Queries","Neil deGrasse Tyson",2021,"StarTalk's big answers"),
      B("The End of Everything (Astrophysically Speaking)","Katie Mack",2020,"Five ways the universe dies"),
      B("Welcome to the Universe","Tyson, Strauss & Gott",2016,"Princeton's famous course in a book"),
      B("Astronomy: Principles and Practice","Roy & Clarke",2003,"Observational foundations"),
      B("Foundations of Astrophysics","Ryden & Peterson",2010,"Clean modern intro"),
      B("High Energy Astrophysics","Malcolm Longair",2011,"The violent universe"),
      B("Accretion Power in Astrophysics","Frank, King & Raine",2002,"How black holes shine"),
      B("The Milky Way: An Autobiography of Our Galaxy","Moiya McTier",2022,"The galaxy tells its own story"),
      B("A Short History of Nearly Everything","Bill Bryson",2003,"Science's greatest hits, hilariously told"),
    ]},

  { domain: "SPACE HISTORY & THE INDIAN SPACE PROGRAMME", icon: "🇮🇳", color: "#1fb84f",
    blurb: "From Thumba's church-turned-launchpad to Chandrayaan-3 on the lunar south pole — and the world race that framed it.",
    books: [
      B("Wings of Fire","A. P. J. Abdul Kalam",1999,"The missile man's autobiography — every Indian engineer's spark"),
      B("Ignited Minds","A. P. J. Abdul Kalam",2002,"Unleashing the power within India"),
      B("India 2020: A Vision for the New Millennium","Kalam & Rajan",1998,"The vision document"),
      B("From Fishing Hamlet to Red Planet","ISRO / P. V. Manoranjan Rao (ed.)",2015,"ISRO's official 50-year history — the definitive source"),
      B("Reach for the Stars: The Evolution of India's Rocket Programme","Gopal Raj",2000,"SLV-3 to GSLV, meticulously reported"),
      B("ISRO: A Personal History","R. Aravamudan",2017,"By one of Sarabhai's original Thumba team"),
      B("My Odyssey: Memoirs of the Man Behind the Mangalyaan Mission","K. Radhakrishnan",2016,"The MOM chairman's account"),
      B("Mission Mangal (MOM accounts)","Minnie Vaid",2019,"'Those Magnificent Women and their Flying Machines'"),
      B("Space. Life. Matter.: The Coming of Age of the Indian Space Programme","Hari Pulakkat",2022,"Modern deep-dive"),
      B("The Vikram Sarabhai story","Amrita Shah",2007,"'Vikram Sarabhai: A Life' — the founder"),
      B("Homi Bhabha: A Life","Bakhtiar K. Dadabhoy",2023,"The atomic-space nexus"),
      B("Satish Dhawan: A Biography","various",2021,"The professor who built ISRO's culture of failure-ownership"),
      B("A Brief History of Rocketry in ISRO","P. V. Manoranjan Rao & P. Radhakrishnan",2012,"Technical-historical record"),
      B("Touching the Sky: India's Space Odyssey","Ajey Lele",2021,"Strategy and milestones"),
      B("Mission Moon: Exploring the Moon with Chandrayaan-1","Pallava Bagla & S. Rao",2008,"India reaches the Moon"),
      B("Reaching for the Stars: India's Journey to Mars and Beyond","Pallava Bagla",2014,"MOM and after"),
      B("The Right Stuff","Tom Wolfe",1979,"Mercury astronauts, mythologised perfectly"),
      B("A Man on the Moon","Andrew Chaikin",1994,"THE Apollo history"),
      B("Failure Is Not an Option","Gene Kranz",2000,"Mission control's iron creed"),
      B("Apollo 13 (Lost Moon)","Jim Lovell & Jeffrey Kluger",1994,"The successful failure"),
      B("Carrying the Fire","Michael Collins",1974,"The finest astronaut memoir"),
      B("First Man: The Life of Neil A. Armstrong","James R. Hansen",2005,"The authorised biography"),
      B("Hidden Figures","Margot Lee Shetterly",2016,"The Black women mathematicians of NASA"),
      B("The Space Barons","Christian Davenport",2018,"Musk, Bezos and the new race"),
      B("Liftoff: Elon Musk and the Desperate Early Days of SpaceX","Eric Berger",2021,"Four flights to survive"),
      B("Korolev: How One Man Masterminded the Soviet Drive to Beat America to the Moon","James Harford",1997,"The Chief Designer"),
      B("Beyond: The Astonishing Story of the First Human to Leave Our Planet","Stephen Walker",2021,"Gagarin's 108 minutes"),
      B("Endurance: A Year in Space","Scott Kelly",2017,"The body's war with orbit"),
      B("An Astronaut's Guide to Life on Earth","Chris Hadfield",2013,"Orbit-tested wisdom"),
      B("Leaving Earth","Robert Zimmerman",2003,"Space stations and the long stay"),
    ]},
  ];
})();
